### ISSUE TITLE
Proposal: Search tree reuse

### ISSUE THREAD

**Issue by Toby-Scantlebury** [LeelaChessZero/lc0#1134]
I intended to propose reusing the search tree between selfplay games during training.

However, `kReuseTreeId` defaults to false for training games, the motivation in #57 given is that it "allows noise to take full effect". Is there an intrinsic reason this has to be the case? Because it feels like a lot of performance is being left on the table.

If tree reuse were ok then part of the search tree could be used between games, allowing training games to explore the opening more thoroughly and/or evaluate fewer nodes.

**Comment by mooskagh** [comment]
We have NN eval cache, so after resetting the tree, the eval doesn't go to GPU for evaluation but is retrieved from the cache. The cache is kept both between moves and between games. Therefore there's no performance hit.

For questions like this, it's recommended to ask them in our [Discord chat](https://discord.gg/pKujYxD) rather than raise a GitHub issue.

I'm closing this issue as there's no issue to solve.
