### ISSUE TITLE
Implement some sort of compression for the networks

### ISSUE THREAD

**Issue by DanielUranga** [LeelaChessZero/lc0#121]
Currently the networks are being stored as float arrays and then gzipped. The code is on:
- https://github.com/LeelaChessZero/lc0/blob/master/src/neural/writer.cc
- https://github.com/LeelaChessZero/lc0/blob/master/src/neural/loader.cc

The generated files are too big and their distribution is problematic.

Several ideas have been proposed, for example:
- Using quantization, possibly with https://www.tensorflow.org/performance/quantization
- Using zfp https://computation.llnl.gov/projects/floating-point-compression

Some histograms for the floats distribution have been rendered: https://cdn.discordapp.com/attachments/438088534755377204/461991110974111754/histograms.7z

The task is to implement some kind of compression scheme for the networks, among with it's saving/loading.

**Comment by gonzalezjo** [comment]
I wrote some stuff to collect data regarding zfp and straight-up dumps of floats. https://github.com/gonzalezjo/lczero-experiments/tree/master/float-compression



If it doesn't run (Windows :(), compile zfp using `make shared` and replace the shared library in `native` with your binary, and the reference to libzfp.so in lib.lua with whatever the library name is. 


Results: With an error tolerance of 1e-5, the 373 MB uncompressed 20b net goes down to 52.4 MB. With bsc (an experimental compressor) ran on the output, a file is produced that is just 49.1 MB in size. If you do this same procedure but with an error tolerance of 1e-4, file sizes drop down to an amazing 38.4 MB on 20 block. 


With 1e-5 + bsc, the 6 block net drops to 8.1 MB. The results are convincing.

**Comment by gonzalezjo** [comment]
In regards to lossless compression, here are my numbers. 


A dump of all the numbers in the weights file for 20B takes you from 373.0 MB uncompressed / 129 MB gzipped (by server) to 111.9 MB uncompressed / 103.9 MB gzipped (by me) 


Running zfp losslessly on the 20b memory dump (settings: ERROR_THRESHOLD = 1 if anyone would like to reproduce. It's possible that there is another, better way of using zfp for lossless compression) increases the file size from 111.9 MB to 115.5 MB. In other words, zfp's lossless compression actually *increased* the file size. 



Running frzip, a lossless float compressor yielded nicer results. From 111.9 MB, frzip brought us down to 102.9 MB. Alone, that's not that amazing, but compared to the plaintext + gzip'd results, it's a an appreciable decrease in file sizes. 


A generic compressor like bsc will not help on frzip's output.

**Comment by gonzalezjo** [comment]
Instead of zfp, I think it might just be worth doing protobufs + a shift to fp16. It seems like it could be a [~60% speedup on CPUs](https://software.intel.com/en-us/articles/performance-benefits-of-half-precision-floats) and potentially a *much* bigger speedup on Volta GPUs. Going from fp16 -> fp32 on unsupported hardware should be easy and inconsequential. 


I've yet to see any research that suggests that the impacts of fp16 on accuracy are anything significant. On the other hand, even a 6% performance - let alone 60% or greater - improvement in performance would more than make up for any decrease in accuracy.

**Comment by Error323** [comment]
Here's a gist using protobuf and 16 bit truncation on the 32bit float data. https://gist.github.com/Error323/42c0d4a671279ee4aa69b4156d877be3 just for reference or a stepping stone.

I think we should enable quantization in tensorflow and go for 8bit per parameter in combination with protobuf, we know it can be done as the TPUs used for gameplay in A0 were 8bit. This will benefit us in three ways:

1. Huge amount of compression from 256x20 373M uncompressed to ~20M 8bit gzip compressed
2. Allow 16b float to work without problems
3. Prepare us for a TensorRT engine which will give us performance on par with TPUs using 1080Ti cards or greater.

Furthermore it would indeed be wise to also store the training parameters (steps, lr, etc) in the protobuf per network so that we have some history or reference.

**Comment by gonzalezjo** [comment]
Seconding @Error323's comment. 

I saw some conversation on Discord stating that int8 could hurt learning. Maybe that's true, but we should at least test it. Besides the obvious bandwidth gains of int8 + protobufs, there's some less obvious perks.

One, it cuts in-memory sizes by one fourth. This is a lot nicer than it sounds. Right now, a 64x6 network is 18.3 MB in memory. You aren't fitting that in an average consumer CPU for a while. When you move to int8, it's 4.575 MB. To put it in perspective, the Apple A11 iPhone chip has 8 megabytes of L2 cache.


Second, AVX512_VNNI will hit Intel processors "soon" (Icelake?) and will work best with int8. It's the same premise as Tensor cores but taken to a less extreme extent. Just a bunch of AVX units that accelerate what was previously done by AVX512BW. Assuming everything is in the cache, that's a 4x increase in performance on future Intel processors.


Third, AVX512BW. It's already a thing on *existing* Intel processors. I think with MKL, you'd get ~20% or more performance on relevant CPUs for practically free. 


Fourth, on Pascal GPUs, you can use dp4a and presumably performance would about quadruple??? I'm not too familiar with GPU programming or CUDNN, but I imagine bandwidth starvation might affect things. Still, super promising!

**Comment by DanielUranga** [comment]
Yes, done by @Error323 on https://github.com/LeelaChessZero/lc0/pull/166 and https://github.com/LeelaChessZero/lczero-training/pull/31.

**Comment by l1t1** [comment]
With bsc: 13.2 MB (28:1 ratio!!!)
gzip: 19.3 MB
7z w/LZMA: 16.3 MB.

how about the result of 7z ppmd?

**Comment by gonzalezjo** [comment]
@l1t1 I no longer have those network files, so I used leelaz-model-swa-12-96000.txt from Leela Zero (Go).


Results using LZMA2 at optimal settings: 



wc -c leelaz-model-swa-12-96000.7z leelaz-model-swa-12-96000.bsc leelaz-model-swa-12-96000.uncompressed.txt 
 14712009 leelaz-model-swa-12-96000.7z
 12067786 leelaz-model-swa-12-96000.bsc
276757452 leelaz-model-swa-12-96000.uncompressed.txt



Using PPMD from 7z with optimal settings: 12432145 leelaz-model-swa-12-96000.7z




Numbers are in bytes. 


bsc arguments are: ./bsc e INPUT_FILE_NAME OUTPUT_FILE_NAME -e2 -p
