### ISSUE TITLE
in callbacks.h best_move->ponder wrong.

### ISSUE THREAD

**Issue by leedavid** [LeelaChessZero/lc0#1214]
in callbacks.h  

void TransformBestMove(BestMoveInfo* best_move) override {
    std::vector<Move> moves({best_move->bestmove, best_move->ponder});
    ConvertToLegacyCastling(head_board_, &moves);
    best_move->bestmove = moves[0];
    best_move->ponder = moves[1];
  }
sometimes best_move->ponder will be 0x0000, then call ConvertToLegacyCastling(head_board_, &moves);  in function ConvertToLegacyCastling will run pos.ApplyMove(0x0000).  will make the ApplyMove function errror.

**Comment by Tilps** [comment]
I don't see any way that ApplyMove can crash because of being given the null move.  Sure it corrupts the board state, but other than that it seems fine.
GetLegacyMove will even return null move if given null move, since it doesn't match either legacy castling.
So despite being quite ugly, I'm not immediately seeing the problem.

**Comment by Naphthalin** [comment]
Author isn't talking about Lc0, but about his personal Xiangqi implementation (according to #960), and has opened several issues here about problems with his own fork. Not a Lc0 issue, closing this.
