### ISSUE TITLE
Android APK Issue

### ISSUE THREAD

**Issue by hangejj** [LeelaChessZero/lc0#1318]
Having issues running the APK app for lc0 on my Android tablet in Droidfish.  
Droidfish recognizes the engine however when I go to analyze the position no engine analysis coming up.  Confirmed that Pondering and Show Computer Thinking options are on.  

Device and screenshot of what I'm seeing.
**Chess Engine Version**-v0.25.1
**Network Weights File**-591226

Device:
**Samsung Galaxy Tab A 7.0,** 32 bit ARMv7, Android 5.1.1(Lollipop) 

**Droidfish 1.82v,** WeightsFile-<built in>, Backend-blas

![2020_05_25_11 24 50](https://user-images.githubusercontent.com/61440059/82852876-1ae8b300-9ed2-11ea-89e0-43ab20cd0e22.jpg)

**Comment by lealgo** [comment]
Hi,
It may be a bit challenging to pinpoint your issue because the APK has no troubleshooting capabilities yet, unfortunately. But we could try this:

1. To get the exact abis as reported by your device. Just to be sure, could you please install the following app and post the screenshot of the second screen here, the one that reads "System"?

https://play.google.com/store/apps/details?id=com.inkwired.droidinfo

2. Try to run just the engine to check it is loading properly. This will require you to be familiar with working from the command line and the Termux app, here:

https://play.google.com/store/apps/details?id=com.termux

And this is the engine (choose the right abi):

https://ci.appveyor.com/api/buildjobs/3q12nsw61se53w9u/artifacts/armeabi-v7a/lc0
https://ci.appveyor.com/api/buildjobs/3q12nsw61se53w9u/artifacts/arm64-v8a/lc0

(The two links are from the wiki: https://github.com/LeelaChessZero/lc0/wiki/Running-lc0-on-Android-with-a-chess-GUI#plain-engine-binaries-for-the-latest-release)

Copy the engine to the root folder of your device. Open Termux and give it storage permissions. Then type this:

```
cp /sdcard/lc0 .
chmod +x lc0
./lc0
```

If you succeed post the screenshot of the commands here.
