### ISSUE TITLE
test 20block net outputs identical Vs for first ply

### ISSUE THREAD

**Issue by killerducky** [LeelaChessZero/lc0#133]
See the bottom of this long from Dubslow: https://pastebin.com/raw/2QfUYK3M 
Every move has `V: -0.0375`
(Ignore the top half of the pastebin, lczero V is actually Q -- average of Vs).

lc0 cudnn backend has the same, and so does lczero.exe (for this the easiest way is to use "go nodes 10" and check the nodes that get only 1 visit so you can see the true raw net value for that move).

This doesn't happen for the other nets we checked. TBD: Check ~~logosgg~~ or scs-ben's 20block. 

Update: logosgg's kb3 net does not have this behavior.

**Comment by dubslow** [comment]
Maybe this should be in lcz-training lol

**Comment by killerducky** [comment]
Tilps pointed out that Error's 8bit quantize test does not have this behavior, Vs were different from each other.
https://discordapp.com/channels/425419482568196106/425419999096733706/465242476081577985

```
(regular)
info string c2c4  (264 ) N:    1056 (+ 0) (P:  9.12%) (Q:  0.01812) (U: 0.02901) (Q+U:  0.04713) (V: -0.0357) 
info string d2d4  (293 ) N:    1216 (+ 0) (P:  7.34%) (Q:  0.02375) (U: 0.02028) (Q+U:  0.04403) (V: -0.0357) 
info string e2e4  (322 ) N:    1983 (+ 0) (P: 14.33%) (Q:  0.02053) (U: 0.02429) (Q+U:  0.04482) (V: -0.0357) 

(8bit)
info string c2c4  (264 ) N:    1013 (+ 0) (P:  9.09%) (Q:  0.01880) (U: 0.03004) (Q+U:  0.04885) (V: -0.1084) 
info string d2d4  (293 ) N:    1071 (+ 0) (P:  7.47%) (Q:  0.02543) (U: 0.02337) (Q+U:  0.04880) (V: -0.1077) 
info string e2e4  (322 ) N:    2267 (+ 0) (P: 14.31%) (Q:  0.02556) (U: 0.02116) (Q+U:  0.04672) (V: -0.1080) 
```

**Comment by dubslow** [comment]
That's only different to within the precision of 8bit floats. But that does indicate that somehow 32bit floats are being trained to cancel each other out in some way??

**Comment by dubslow** [comment]
https://pastebin.com/raw/vq79GvFv

https://pastebin.com/raw/bNzgDxpc

https://pastebin.com/raw/4LhUzZ9n

Each of these is "test 50 nodes given an FEN for a position, then test 50 nodes for the same position with uci history instead of FEN". First two use the position after 1. f4 and 1. Nc3 respectively, and show the problem as well; the third shows the position where should be played Qd3 (g6d3) from Kramnik vs Leko 2004, and doesn't show the same problem (FEN first ply values are all different). Most astonishingly to me, *without* history, the policy head correctly identifies the correct move (despite search not liking it so much), while *with* history, we get policy much more similar to other nets with history (in particular, not so hot on the correct move).

**Comment by cn4750** [comment]
Apparently test9 nets have this issue too: [https://pastebin.com/4Tz5Mfyi](https://pastebin.com/4Tz5Mfyi)
Credit to a_pleasant_illusion on Discord.

**Comment by dubslow** [comment]
a_pleasant_illusion demonstrated that test9, the 6b nets, also had this: https://pastebin.com/4Tz5Mfyi

So this isn't as bad as could have been thought.

**Comment by cn4750** [comment]
Apparently even the main nets had this issue according to Discord user mwardcusd:

> so it looks like it starts fixing itself around id 251, before that all are equal except for 1

**Comment by mooskagh** [comment]
Probably not actual anymore (feel free to reopen if it is)
