### ISSUE TITLE
 "Stopped search: Reached visits limit" floods logfile

### ISSUE THREAD

**Issue by Naphthalin** [LeelaChessZero/lc0#1507]
_posted by user Tiranasta on Discord 2021-01-27 18:32_

> When using a log file and running with a RAM limit, if the node limit is reached in infinite analysis mode Leela starts outputting the "Stopped search: Reached visits limit" message to the log file over and over again at such a rapid rate that the log file can quickly reach tens of gigabytes in size before the user even notices there's a problem. In positions with a forced mate, the limit can be reached within moments of starting a fresh search.

[didn't try to reproduce it, just reporting]

**Comment by DU-jdto** [comment]
Tiranasta here. The Watchdog thread keeps checking the stoppers even after stop_ is set to true for as long as ok_to_respond_bestmove_ is false, which is why the line keeps getting repeated. And as for the sheer speed at which the files grows once the visits limit is reached, the wait_for function on search.cc line 908 is non-blocking once stop_ is true, so the Watchdog thread will loop as quickly as the hardware can manage.
