### ISSUE TITLE
Accuracy of Q updates

### ISSUE THREAD

**Issue by killerducky** [LeelaChessZero/lc0#186]
Quoting RedDenver from Discord:

This is a very minor point, but thought I'd mention it in case it ever comes up: Once search has visited a child node ~8.3M times, the Q value will stop being updated. 
Here's the reasoning: Q is updated using the Welford method: 
`q_ += (v - q_) / (n_ + 1);`
 and since 
`q_`
 is a single precision float, once 
`n_ + 1`
 reaches 2^23=8388608 that division term will always be zero.
This won't produce an error, so it's only a problem if you're doing long time controls on very fast hardware.

**Comment by jjoshua2** [comment]
So sounds like its a 32 bit float. No downside to making it 64 bit and seeing if that helps right?

**Comment by RedDenver** [comment]
I don't think just making the calculation a double will help as the value will be truncated when stored back into the float.

The obvious way to fix it is to make `q_` a double, but that adds 4 bytes to every node.

**Comment by Tilps** [comment]
Given we are happy with using fp16 eval - I think its going to be quite some time past 8 million before the error margin in Q exceeds the initial error that comes from starting with fp16 values. (But while I think that it would be nice for someone to actually do the math :P)

Even if Q does stop updating - visits should keep U dropping so search should continue to switch between subtrees to visit.  I would also think that by the time we get to 10million + visits, our Q value confidence should be pretty high, so if it stops changing, it should hardly be significant in the final outcome.  If we're in a position where the top 2 moves Q values are really so close that we would need smaller confidence bounds to distinguish them, it probably doesn't matter what we play. The important part is that less visited lower confidence items are still getting some visits so that their Q value might converge on something higher and end up getting lots of visits as a result.

**Comment by RedDenver** [comment]
I agree Tilps. There's probably a few cases like TCEC, WCCC, or making opening books where this might be an issue, but I think it's minor until there's more cases of 8M+ visits.

**Comment by Videodr0me** [comment]
This should not lead to a slow down, I agee with Tilps. The old way of accumulating in w had a similar problem (w overflow, and dividing by largen). I think its not needed, but we coud fix by using a min delta just high enough to change q the smallest possible amount.

**Comment by RedDenver** [comment]
This shouldn't lead to a slowdown, just a question of accuracy of Q

**Comment by dubslow** [comment]
Even the accuracy problem is easily solved, just add a `std::map<Node*, float>` to `NodeTree` which can serve as additional storage for the rare nodes that exceed 8 million visits (though I expect that it would make little difference in practice either).

**Comment by RedDenver** [comment]
I don't see how a map from node to float helps in this case.

**Comment by dubslow** [comment]
```
Node::UpdateQ(float newval) {
  if (this->n_ < 8000000)  { // or whatever the exact point is
    this->q_ = FormulaUpdate(this->q_, this->n_, newval); // I forget the actual formula, but you know what I mean
  } else {
    other_q = NodeTree::overflowed_q_map_[this];
    NodeTree::overflowed_q_map[this] = FormulaUpdate(other_q, this->n_ - 8000000, newval);
  } 
}
```

```
Node::GetQ() {
  if (this->n_ < 8000000)  { // or whatever the exact point is
    return this->q_;
  } else {
    float this_fraction = 8000000/this->n_;
    return this_fraction * this->q_ + (1 - this_fraction) * NodeTree::overflowed_q_map_[this];
  }
}
```

Not as pretty as it should/would be, but you get the idea.

**Comment by RedDenver** [comment]
I still don't understand how that helps. Did you mean to map from node to a double?

**Comment by dubslow** [comment]
No. It helps because presumably the `other_q` being used as overflow storage doesn't match the first 8000000 playouts to all 23 bits of significand precision.

(Now that you mention it, I think perhaps the combining step might need to promote to doubles, but the extra storage most certainly can and should be a float.)

**Comment by RedDenver** [comment]
I like the idea of mapping to another higher accuracy Q value, but using a float and averaging only doubles the number of nodes from ~8.3M to ~16.6M until you have accuracy issues again. Using a double in the map (and ignore the float Q value) give ~4.5T nodes before accuracy loss. But there's probably a way to use a float in the mapping where instead of averaging, the float is used as higher order bits like having a double but splitting it into two 4 byte variables.

**Comment by RedDenver** [comment]
After thinking about it for a bit, I think we should either leave it as is and accept the accuracy loss or use an int32 because it doesn't have to find the mapping (I think that the math will be faster than the map lookup but am not certain) and uses the same memory of 4 bytes as the float already does.

**Comment by dubslow** [comment]
I'm on board for leaving it for now, and using a 32 bit int is probably a good idea too. We really don't need 8 bits of exponent.

**Comment by RedDenver** [comment]
As long as I'm thinking about it here's a proposed implementation for int32:
```
int32_t q_int_; //signed 32 bit int representation of Q
...
Node::UpdateQ(float newval) {
  int32_t v = static_cast<int32_t>(newval * 0x7FFFFFFF); //2^31-1 = 0x7FFFFFFF
  q_init_ += (q_init_ - v) / (n_ + 1);
}

Node::GetQ() {
  return static_cast<float>(q_init_) / 0x7FFFFFFF;
}
```

**Comment by Videodr0me** [comment]
@Dubslow Using overflow nodes seems overengineered to me, for something which might not even be a real problem.

An alternative to RedDenver's proposal, is to address the issue by limiting n :
```
uint32_t n_update = (n_ < max_div) ? n_ : max_div;
q_ += (v - q_) / (n_update + 1); 
````
We just choose max_div as the largest number that keeps a delta of our choosing after division non zero.

**Comment by RedDenver** [comment]
@Videodr0me You're basically changing from an average over all nodes to an average over the last `max_div` nodes. see: https://stackoverflow.com/a/50854247

That's not necessarily a problem but just like leaving it as-is, it won't be quite the right answer.

**Comment by Videodr0me** [comment]
@RedDenver 
Yes! But thats deliberate, its the only solution that does not just kick the can further down the road. I did a lot of experiments on various moving-average schemes: https://github.com/Videodr0me/leela-chess-experimental/wiki/Backpropagation:-Q-Moving-Average
and thresholding this by the max number that would register a differences should work regardless of base precision of Q. Its an alternative, not saying its "better", but it avoids all the casting.

**Comment by RedDenver** [comment]
@Videodr0me I guess that's fine but it's just a switch from leaving it as-is, which only averages the earlier nodes, to max thresholding, which only averages the later nodes.

**Comment by bjbraams** [comment]
For anybody's general interest I note that this precision issue motivated the technique of compensated summation, more often known as Kahan summation. It involves a pair of 32-bit floats rather than just one float to store the value of interest. In practice, therefore, one does not use Kahan summation for 32-bit floats; one just uses a 64-bit double. If one does use Kahan summation then one has to worry about compiler optimization treatments, as I found some time ago in a Fortran setting.
http://compgroups.net/comp.lang.fortran/compensated-kahan-summation-and-compilers/600743

**Comment by Videodr0me** [comment]
@RedDenver Just one more thought. I think "only averages the later nodes" is somewhat misleading in this particular situation. As at the limit of Q's precision (no matter what that is, just assume n is large enough), the information gain from not thresholding is 0. Which is different from normal moving average situations where addings samples would still yield information. But thats not really important, just wanted to throw an alternative in, but i am fine will your approach as well.

Generally i think its still a non issue, as @Tilps correctly pointed out.

**Comment by RedDenver** [comment]
@Videodr0me That's a good point. I guess it comes down to use case. If it's mostly high child node counts from TCEC, WCCC, or generally just match play, then your approach makes sense. If it's more very long analysis or opening book creation, then mines probably makes more sense.

Either way, I agree it's a non-issue for now.

**Comment by oscardssmith** [comment]
Could we implement the `int32` solution? It seems pretty clean and especially with the 20 series out, the 8 million nodes needed for this to occur will happen after less than a minute on consumer grade hardware.

**Comment by mooskagh** [comment]
As investigated in #328 (and as said above in this thread), Q update doesn't seem to be an issue.
There is some effect which causes Lc0 to stick to the bestmove and not explore other moves, but it doesn't seem to be related to Q precision.

Closing for now.

**Comment by oscardssmith** [comment]
That testing only went up to 1m nodes which is 1/8th the nodes needed for the full effect to be seen.
