### ISSUE TITLE
Invalid move a1a1

### ISSUE THREAD

**Issue by CMCanavessi** [LeelaChessZero/lc0#238]
Got the following in google colab:

```2018/08/07 00:26:17 lc0_main.go:537: serverParams: [--tempdecay-moves=20 --temperature=1 --cpuct=1.2 --fpu-reduction=0.0 --policy-softmax-temp=1.0]
2018/08/07 00:26:17 lc0_main.go:540: Starting match
2018/08/07 00:26:17 lc0_main.go:549: Starting match
2018/08/07 00:26:17 lc0_main.go:322: launching 1
2018/08/07 00:26:17 lc0_main.go:332: launching 2
2018/08/07 00:26:17 lc0_main.go:348: writing uci
2018/08/07 00:27:21 lc0_main.go:394: Error decoding: a1a1 for game:

1.c2c4 e7e6 2.b1c3 d7d5 3.d1a4 c8d7 4.a4d1 d5d4 5.c3b1 c7c5 6.g2g3 g7g5 7.e2e4 h7h5 8.h2h3 b8c6 9.d2d3 h5h4 10.g3g4 f8d6 11.f1g2 f7f6 12.g1e2 e6e5 13.a2a3 g8e7 14.b1d2 e7g6 15.a1b1 a7a5 16.b2b3 d8b8 17.d1c2 g6f8 18.c2d1 c6e7 19.e1g1 f8e6 20.f1e1 e7g6 21.a3a4 d6c7 22.d2f1 b7b6 23.f1d2 g6e7 24.d2f1 e7c6 25.f1h2 e6f8 26.c1d2 c7d6 27.d2c1 b8c7 28.h2f1 e8c8 29.f1h2 c8b8 30.g2f3 d7c8 31.f3g2 c8b7 32.g2f3 c6b4 33.f3g2 b7c8 34.c1a3 b4c6 35.a3c1 c7d7 36.c1d2 b8c7 37.d2c1 f8e6 38.h2f1 h8e8 39.f1h2 e6f8 40.h2f1 c6b4 41.c1a3 b4c6 42.a3c1 c6b4 43.c1a3 e8e6 44.a3c1 b4c6 45.f1d2 d7e8 46.b1a1 e6e7 47.d2b1 c7b8 48.b1a3 f8e6 49.a3b5 d6c7 50.c1d2 c6b4 51.d2c1 d8d7 52.b5a3 d7d8 53.a3c2 e6f8 54.c2a3 f8e6 55.a3c2 b4c6 56.c2a3 e6f8 57.a3b5 c8b7 58.c1d2 d8d7 59.g2f3 c7d8 60.f3g2 c6b4 61.d1b1 b4a6 62.e2c1 f8e6 63.c1e2 a6b4 64.g2f1 b4c6 65.f1g2 e6f8 66.b1d1 e7f7 67.b5a3 c6e7 68.a3b5 e7c6 69.b5a3 b7c8 70.d1b1 f8e6 71.a3b5 e8f8 72.b1d1 c6b4  *
2018/08/07 00:27:21 lc0_main.go:336: Waiting for candidate to exit.
2018/08/07 00:27:21 lc0_main.go:326: Waiting for baseline to exit.
2018/08/07 00:27:21 lc0_main.go:552: playMatch: chess: invalid move a1a1```

**Comment by borg323** [comment]
From the discord report this is a main server match game (cpuct=1.2), probably game <http://lczero.org/match_game/506649> the only one from @CMCanavessi in match <http://lczero.org/match/595>that didn't finish and the time stamp fits.

**Comment by Hungry-Caterpillar** [comment]
Creating backend [multiplexing]...
Creating backend [cudnn]...
Loading weights file from: networks\12ef5704fef57c4e73fb209911491cf71bdf462f2c87233b4185ff89e0c1cc2c
Creating backend [multiplexing]...
Creating backend [cudnn]...
2018/08/11 15:25:30 lc0_main.go:498: Error decoding: a1a1 for game:

1.d2d4 g8f6 2.c2c4 e7e6 3.g1f3 f8e7 4.c1f4 e8g8 5.b1c3 d7d5 6.e2e3 b8d7 7.f1e2 d5c4 8.e2c4 c7c5 9.e1g1 c5d4 10.d1d4 a7a6 11.a2a4 b7b6 12.f1d1 c8b7 13.f3e5 e7c5 14.d4d3 d7e5 15.f4e5 d8d3 16.c4d3 f8c8 17.d3e2 b7c6 18.e5d4 c5d4 19.d1d4 g8f8 20.f2f3 f8e7 21.e3e4 a6a5 22.g1f2 f6d7 23.f2e3 d7c5 24.a1a3 c8d8 25.d4c4 a8c8 26.b2b4 a5b4 27.c4b4 c5d7 28.c3d1 c8a8 29.d1b2 d8b8 30.a3c3 d7c5 31.e2d1 c6e8 32.h2h4 c5a6 33.b4b3 a6c5 34.b3b4 c5a6 35.b4b3 a6c5 36.b3b4 *
2018/08/11 15:25:30 lc0_main.go:440: Waiting for candidate to exit.
2018/08/11 15:25:30 lc0_main.go:430: Waiting for baseline to exit.
2018/08/11 15:25:30 lc0_main.go:660: playMatch: chess: invalid move a1a1

LC0 v0.16.1-dev built Aug 10 2018 (testserver match)

Args: [E:\lc0_cuda/lc0 uci --backend=multiplexing --tempdecay-moves=20 --temperature=1 --cpuct=2.4 --fpu-reduction=0.0 --policy-softmax-temp=1.0 --weights=networks\27301386e5fd474ad32d5aeb54812ee2418d3f1ba2cc85e6e23281b545ca8ca3]
2018/08/11 15:24:58 lc0_main.go:436: launching 2
lc0 is never quiet.
Args: [E:\lc0_cuda/lc0 uci --backend=multiplexing --tempdecay-moves=20 --temperature=1 --cpuct=2.4 --fpu-reduction=0.0 --policy-softmax-temp=1.0 --weights=networks\12ef5704fef57c4e73fb209911491cf71bdf462f2c87233b4185ff89e0c1cc2c]


Looks like the game concludes with a 3 fold repetition draw. As a draw is value 0 and I assume square a1a1 is 0 there maybe a correlation ?

**Comment by jkormu** [comment]
My client also stopped last night due to invalid move a1a1:

uciok
Creating backend [multiplexing]...
Creating backend [cudnn]...
Creating backend [multiplexing]...
Creating backend [cudnn]...
2018/08/12 01:39:30 lc0_main.go:394: Error decoding: a1a1 for game:

1.e2e3 e7e6 2.a2a3 f8e7 3.g1f3 d7d5 4.c2c4 g8f6 5.b1c3 e8g8 6.d2d4 b8d7 7.c4d5 e6d5 8.f1d3 e7d6 9.c3b5 d6e7 10.b5c3 c7c6 11.e1g1 e7d6 12.d1c2 f8e8 13.f1e1 h7h6 14.c1d2 d7b6 15.h2h3 c8e6 16.f3e5 a8c8 17.b2b4 b6c4 18.d3c4 d5c4 19.e3e4 a7a5 20.b4a5 d6c7 21.a5a6 b7a6 22.e5f3 c8b8 23.e4e5 f6d7 24.c2e4 c7a5 25.e4c6 d7b6 26.a1c1 a5c3 27.d2c3 e6d5 28.c6d6 d5f3 29.d6d8 e8d8 30.g2f3 b6d5 31.c3a5 d8c8 32.a5b4 c4c3 33.c1c2 c8c4 34.e1c1 g8h7 35.g1f1 c4d4 36.b4c3 d4d3 37.c3d2 d3f3 38.c2c5 f3d3 39.f1e2 b8b3 40.a3a4 d3d4 41.c1c4 d4c4 42.c5c4 b3h3 43.c4c5 d5e7 44.c5c7 e7g6 45.f2f4 h7g8 46.c7c8 g8h7 47.c8c7 h7g8 48.c7c8 g8h7 49.c8c7 *
2018/08/12 01:39:30 lc0_main.go:336: Waiting for candidate to exit.
2018/08/12 01:39:30 lc0_main.go:326: Waiting for baseline to exit.
2018/08/12 01:39:30 lc0_main.go:552: playMatch: chess: invalid move a1a1

**Comment by mooskagh** [comment]
a1a1 is returned when `lc0` is forced to move when it's a draw (threefold repetition). It's a bug, but also there is a bug in client which didn't detect that it's a threefold repetition.
(it seems that it's the same en passant bug which was recently fixed in lc0)

Game from the last comment: https://lichess.org/95tDheHC

**Comment by Hungry-Caterpillar** [comment]
Thanks for the update !
Not sure why this is a bug in the client. If you expect that the client knows and takes care of 3 fold repetitions then the engine should keep playing (legal moves) until the client tells it to stop. The main issue is that the engine sends an illegal move and not that the client doesn't recognize 3 fold repetition.
I don't think its a good idea to expect the client to take care of the engine faults - do we expect that all GUI's as well fix faults from lc0  ?
If the engine is fixed is there any need to do anything in the client ?

I am also not sure how this would be fixed in the client given that this is done immediately after the best move is received - before the result if that is ever sent in this case. The client when it detects an error then needs to decide whether the game would have finished with a final result (mate, stalemate or draw through 50 or 75 move rule or 3 or 5 repetitions). If it can't decide then it would have to reject that game and request a new session from the server.

Given that the client is in most cases left unattended it maybe a better solution to reject any games with faulty moves from the engine and request a new session other then logging an error and waiting for a new input causing a timeout (no more UCI output is coming from the engine) which after 3 attempts kills the client.

(I just received my second a1a1 error....)

**Comment by mooskagh** [comment]
I agree that the fact that engine responds with invalid move when it's asked for a move from threefold repetition position is a bug.

Fix should be like that (feel free someone to send a PR, or I'll do that later this week):
```diff
void EngineController::Go(const GoParams& params) {
  if (!tree_) {
    SetPosition(ChessBoard::kStartingFen, {});
  }

  auto limits = PopulateSearchLimits(tree_->GetPlyCount(),
                                     tree_->IsBlackToMove(), params);

+ if (tree_->GetCurrentHead()->IsTerminal()) tree_->TrimTreeAtHead();

  search_ =
      std::make_unique<Search>(*tree_, network_.get(), best_move_callback_,
                               info_callback_, limits, options_, &cache_);

  search_->StartThreads(options_.Get<int>(kThreadsOption));
}
```

But the fact that client sometimes doesn't detect threefold is also a bug.

**Comment by mooskagh** [comment]
I think that was fixed, but cannot find the PR.

**Comment by oscardssmith** [comment]
This was fixed, should be closed.
