### ISSUE TITLE
lc0 crash 

### ISSUE THREAD

**Issue by AlingoAlingo** [LeelaChessZero/lc0#248]
![img_20180812_085930](https://user-images.githubusercontent.com/33194033/43999380-0a51752e-9e14-11e8-84df-5c0c0aa0a87a.jpg)

**Comment by AlingoAlingo** [comment]
lc0 crash many times

**Comment by dubslow** [comment]
That's unfortunate, but doesn't tell us any reason about why it happened.

**Comment by AlingoAlingo** [comment]
It happens when I used the interface from deep fritz 13 and 14

**Comment by AlingoAlingo** [comment]
Something is wrong with the lc0 engine.
thanks

**Comment by all12** [comment]
Something is wrong with the lc0 engine.
thanks

-I have the same problem with LC0 and ChessBase 14 GUI, Chess Assistant GUI, Fritz 15 and 16 GUIs and Chess OK Aquarium GUI.

-sometimes LC0 freezes the GUI, 
-sometimes it doesn't display the infinite analysis,
-sometimes it stops even to analyse,
-sometimes it stops to play his move during a tournament or match,
-also these things leads to endless loses on time.

-v0.10.0 was great but v0.16 and v0.17 are really buggy.

-Also we are missing a video how to implement and run LC0 in the ChessBase/Fritz/ChessOk Aquarium GUIs.

-Please write exactly what hardware do you use, because I want compare it to my hardware.
Maybe the same gpu and so on.
Which Windows / OS?
SSD or HDD??
GUIs you have used?
Does it work with lc0 v0.10.0?

**Comment by AlingoAlingo** [comment]
I use  asrock motherboard, i5 processor generation 6,  R9 380 video card

**Comment by AlingoAlingo** [comment]
windows 10

**Comment by AlingoAlingo** [comment]
lco v0.10.0  It works perfectly for me

**Comment by mooskagh** [comment]
Not enough information to reproduce.
