### ISSUE TITLE
lc0 bad scaling

### ISSUE THREAD

**Issue by pw31** [LeelaChessZero/lc0#308]
We have now two independent confirmations that the scaling of lc0 saturates around 50k nodes/move:

1) From https://docs.google.com/spreadsheets/d/1XSJiCcQpCLv0fNwrUn7jXjdkZFU63YFEWpdXv6dSSg0, look at the **blue dashed line**:
![image](https://user-images.githubusercontent.com/18750275/44626947-b6c04600-a91d-11e8-925a-baf19ea4a8da.png)

2) From https://docs.google.com/spreadsheets/d/1ZAIuHR6n-5JTxKQc0XUSx1jyUrgVEcj8DNLKA7-urBw:
![image](https://user-images.githubusercontent.com/18750275/44626955-c3dd3500-a91d-11e8-82bd-dafe84f3bf66.png)

This seems to be confirmed by recent TCEC bonus games and CCCC test games.  Although lc0 has been measured to have reached e.g. Stockfish 8 (4 cores) level in bullet or blitz games, which it has trained for, it performs significantly worse on longer time-control and/or on strong hardware.

It seems to me that lczero is not affected so much by this problem, but only lc0 is.  So the problem must be somewhere in the search algorithm, I guess.  The changes made to lc0 seem to benefit leela to get more nodes/sec and boost performance in bullet games, but they might hamper performance and scaling at long TC / strong hardware.

Questions:

1. What is the difference between lczero and lc0 search algorithm? Can anybody please explain?
2. How can this problem be addressed?
3. How can people in the community contribute to help with meaningful tests?

Thank you

**Comment by jjoshua2** [comment]
1. The main difference is default search parameters, and what nets were popular at the time.
2. Either search tweaks or better nets.
3. Different search params could be tried. For example does cpuct=4 cause a stragetic test suite to scale better with time? (since its possible for one person to easily test scaling with that unlike very high node games)

**Comment by mooskagh** [comment]
Would be nice to have some other tests, not only Elo, but e.g. whether Leela changes move often after 500000 visits, or whether it changes it to better one, or in positions that it doesn't plays optimally, how N and Q of every move changes with visits, etc.

**Comment by xghostxx** [comment]
Just going to point out a few things:

In short TC games, Leela dominates, namely because A/B engines don't have enough time to think. This is why we see the performance we do vs SF 8 or other engines.

In (significantly, and I really do mean significantly) longer TC games, it is not Leela that is performing worse. It is (at least in part), that we're finally giving the AB engines some breathing room and they aren't blundering in silly ways.

Most AB engines are not supposed (or able) to play incredibly strong reaching only lower depths (notable exceptions being maybe Komodo 7 and Prodeo). They need to reach reasonable depths (20+) to play in non-silly ways. 

It also doesn't help that people cherrypick the most aesthetic games to display, which leads to a sort of general misconception that Leela dominates the chess scene a lot more than it actually does.

Also, it is not that Lczero is not affected by not scaling well at higher nodes. It definitely is. It is just that it is much faster and easier to run tests to reach high nodes with Lc0. The tests could also be run with Lczero but it is rather time consuming.

And on a final note with regards to ELO, classic ELO, rapid ELO, and blitz ELO are all different things (because of different time controls). Dominance in one area is not definitely not indicative of dominance in all or other areas, even if they are similar (well, at least, not yet). Check out: 2700chess.com

**Comment by Naphthalin** [comment]
Cpuct scaling, tuning the scaling parameters and several tests have shown that Lc0 still changes its mind often enough at much higher node counts, plus Lc0 at a few million nodes is now on par with SF which isn't the case at 50k npm only -- so I would say we have enough evidence that this isn't an issue anymore, especially with recent improvements on broader policies.
