### ISSUE TITLE
Should we add check extension for lc0?

### ISSUE THREAD

**Issue by leedavid** [LeelaChessZero/lc0#319]
As all of us know, the stockfish chess has check extension, but mcts lc0 does not have.
When I test lc0 some times lost for without check extension, so I suggest we can add check extension for lc0.

**Comment by jjoshua2** [comment]
This is a type of QS right? It seems like that could save a lot of NN evals... And maybe allow reaching TB several moves earlier if done that way...

**Comment by leedavid** [comment]
yes，QS is very important hack in chess engine.

**Comment by Videodr0me** [comment]
QS is different from check extensions. In a discrete sampling algorithm (MCTS as used in lc0) it is not "clear" what extending checks really means. I tested a variant that gives checks a bonus in the PUCT formula, which did not get me any gain outside the error-bars. Also, the NN can learn this on its own by just ouputting higher policy values for checking moves, and I would generally be cautious implementing schemes which address things the NN could figure out by itself eventually.

Other schemes, e.g. a QS like search at the leaves, maybe with a smaller, and thus faster pilot NN or even a full a/b search at the leaves that also extends checks (or alternatively at root with mcts extensions at the a/b leaves) is another matter altogether and might work. Much room for experimentation.

**Comment by jjoshua2** [comment]
I was thinking of skipping the nn eval for intermediate captures and only
evalbfinal just like an engines. Check extensions would be similar so it
finds perpetuals for the nn

**Comment by jhellis3** [comment]
Instead of coding a check extension in search, it would probably be better to calculate a checkers bitboard for each position, pass that as an input plane, and let the NN decide what to do with the information.

Also note that with just checkers and legal move count the NN can identify checkmate & stalemate trivially (should it choose to do so).  Legal move count is also useful for identifying forcing variations.
