### ISSUE TITLE
Test higher U and Q precision

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#328]
Multiple people reported recently that Lc0's strength almost doesn't grow when number of nodes per move is above 400 000.

Some time ago when in-place Q update was implemented (`Q = somefunction(old Q, V, N)` rather than `Q = W/N`), it was argued that we may have possible loss of precision at high node count which will prevent update of Q completely.

Those arguments were discarded with theoretical calculation back then, but now I think it worth checking more thoroughly.

So, if someone has time, could you check whether:
1. Reverting Q update to `W/N` helps
2. Makeing Q and U `double` rather than `float` helps.

**Comment by oscardssmith** [comment]
Can you link the first PR? Also, how would this be tested given that it only effects long tc?

**Comment by mooskagh** [comment]
https://github.com/LeelaChessZero/lc0/pull/56/files

**Comment by dubslow** [comment]
What are the sample sizes with those scaling tests? I'd never seen anything more than 100 games, which is totally meaningless for such a comparison (and of those, as many showed strength gain as didn't).

**Comment by mooskagh** [comment]
100 games test is better than 0 games test. It's not "totally" useless even if it's not very indicative.

Also instead of Elo testing, some simpler tests may be run.
E.g. doing `go infinite` and comparing frequency of bestmove change after 500000 nodes, or doing other ways to compare distribution of moments when bestmove changes.

**Comment by RedDenver** [comment]
Here's the issue discussing the accuracy with some potential fixes: #186

**Comment by oscardssmith** [comment]
The int32 version looks like the simplest solution without memory impact.

**Comment by borg323** [comment]
Did a test on colab with default lc0 options, a 6b net and 100k nodes per move, master against #349. Only managed to finish 156 matches:
```
Score of lc0_master vs lc0_pr349: 21 - 23 - 112  [0.494] 156
```
for an insignificant difference of 4 elo. 100k nodes were chosen because they show a small difference in evaluation of the start position between master and #349. The next test will be with 1M nodes pr move.

The sheet used is: <https://cdn.discordapp.com/attachments/425419999096733706/489553145001672705/Test_lc0_PR_v0_2.ipynb>

**Comment by jjoshua2** [comment]
You might consider using puct=4 at a million to make it more likely for the
engine to be able to switch best move after 200-400k playouts, and is
probably stronger than defaults as well.

**Comment by ddobbelaere** [comment]
As the goal of this issue seems to be the investigation of the accuracy of Q and U at high nodes, isn't it possible to just compare them directly and check if they are really different after an equal number of nodes (for a certain number of test positions)?

I know due to batching and multithreading that the MCTS search is not really deterministic, but for such high node counts it shouldn't make much of a difference I guess (visit distribution should be more or less the same).

**Comment by borg323** [comment]
Repeated the previous test with 1M nodes per move, with no change (but fewer games):
```
Score of lc0_master vs lc0_pr349: 1 - 1 - 22  [0.500] 24
```

**Comment by hans-ekbrand** [comment]
47 games @ 200K nodes per move:

```Score of lc0_master vs lc0_pr349: 9 - 5 - 33  [0.543] 47```

**Comment by borg323** [comment]
Another test with 1M nodes per move, with a more unbalanced book, otherwise as above:
```
Score of lc0_master vs lc0_pr349: 2 - 2 - 16  [0.500] 20
```

**Comment by mooskagh** [comment]
Seems that conclusion is that the current version is not weaker than version with float, right?
Would be also interesting to check how often bestmove change happens after 500000 visits with and without that patch. (e.g. whether claims that bestmove never changes after 400000 visits is true).

**Comment by Videodr0me** [comment]
This is basically untestable. It is unknown if more or less best move changes is a good or a bad thing. Also note that all engines e.g. a/b searchers like SF tend to have fewer best move changes per time unit as they search deeper. Also i would suspect that policy spread has a mucher larger effect than q update accuracy in that respect. Generally, meaningful results are hard to come by, due to low sample sizes at high visit searches. If there really is a problem with leelas scalability (i am not yet convinced) then i am afraid the reasons have to be addressed via learning. MCTS is more or less a (fine) calibration tool for the NN policy - at that it generally has a hard time overturning a "flawed" policy that just does not "understand" the position.

**Comment by RedDenver** [comment]
@Videodr0me This isn't untestable, as @ddobbelaere mentioned above there's a straight-forward way to test how big of a difference between U and Q as float vs double. If there's no difference, then we can rule out U and Q accuracy as a cause of the suspected scalability issue.

But I recommend we first establish that there is a scalability issue and have test cases that are repeatable where the scalability is shown to be poor. Then we'll have a baseline from which to test possible causes and fixes.

**Comment by borg323** [comment]
Another 1M nodes test with net scs-32x4-swa1-600000.pb.gz:
```
Score of lc0_master vs lc0_pr349: 3 - 1 - 34  [0.526] 38
```

**Comment by mooskagh** [comment]
Should we conclude that there is no Q and U precision problem? (at least as early as at 400000 nodes)

**Comment by RedDenver** [comment]
I don't think there's been enough evidence to make any conclusions either way. We need whoever is saying that's there's a scaling issue to join this discussion (jjosh? Aloril? I can't remember).

**Comment by mooskagh** [comment]
In the context of whether it blocks v0.18, declaring that as not an issue. (E.g. we are not going to do anything about that in v0.18).
