### ISSUE TITLE
CLOP time management for v0.18

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#367]
We have gazillion of parameters now, including new immediate-time-use
Would be nice to have it clopped both for play with and without ponder.

**Comment by zz4032** [comment]
Tuning results:

Version: LC0 v0.18-dev Id 11262
2nd engine: asmFish

TC: 22.5s+0.125s/move
Average nodes on opening moves: 1500

Games in tuning: 2631

Fixed parameters:
Cpuct MCTS option = 2.7 (standard: 3.4)
First Play Urgency Reduction=1.1 (standard: 0.9)
Policysoftmaxtemperature=2.3 (standard: 2.2)

Values picked from previous tuning. Shouldn't matter much for this tuning.

Parameters (standard/tuned):
```
Scale thinking time = 2.62/2.4
Time weight curve peak ply = 26.2/27.4
Time weight curve width left of peak = 82.0/83.5
Time weight curve width right of peak = 74.0/74.9
```

Notes:
No clear convergence because of too many parameters but I think default parameters can be considered as confirmed by this tuning.
_______________________________________________________

Tuning results:

Version: LC0 v0.18-dev Id 11262
2nd engine: asmFish

TC: 22.5s+0.125s/move
Average nodes on opening moves: 1500

Games in tuning: 1171

Fixed parameters:
Scale thinking time = 1.0

Parameters (standard/tuned):
`Fraction of saved time to use immediately = 0.0/0.4`

Notes:
No clear convergence, but in clop diagram it's visible that values close to upper bound 1.0 are slightly worse. That's why clop picked 0.4 (below average 0.5). Also a sign that not much Elo gain is expected from tuning.

**Comment by zz4032** [comment]
Let me redo the "Fraction of saved time to use immediately" tuning today. I just found out that Clop in Linux needs parameters without spaces. I've done recompiling lc0 previously with renamed uci options but not for the latest two tunings (this one and test20 cpuct tuning).

**Comment by zz4032** [comment]
Tuning results after 1100 games:
Fixed parameters: Scale thinking time = 1.0
Parameters (standard/tuned):
```
Fraction of saved time to use immediately=0.0/0.62
```
Gauntlet with asmFish vs. various lc0 settings:
```
   # PLAYER            :  RATING  ERROR  POINTS   GAMES
   1 lc0_SM1.0_F0.6    :       0     24   200.0     400
   2 asmFish           :       0   ----   416.5     800
   3 lc0_SM1.0_F0.0    :     -14     37    96.0     200
   4 lc0_SM2.4_F0.0    :     -44     32    87.5     200
```
SM = Slowmover / 'Scale thinking time'
F = `Fraction of saved time to use immediately'
Clop diagram:
![clop](https://user-images.githubusercontent.com/11909324/45927112-52999d80-bf2e-11e8-84d0-6cacf462f505.png)
It looks like values close to 1.0 are not bad either. Probably that's an indicator that further tuning of TM curve parameters makes sense.
I think we should go with slowmover=1.0 and immediate-time-user=0.6.

**Comment by fli** [comment]
```
   # PLAYER             :  RATING  ERROR  POINTS  PLAYED   (%)  CFS(%)
   1 lc0-fraction50     :     8.9   16.3   137.0     264    52      69
   2 lc0-fraction100    :     1.8   16.4   133.0     264    50      80
   3 stockfish          :   -10.6   16.5   126.0     264    48     ---
```
I ran some tests, with 90s+0.5s TC and slowmover=1, and it shows that immediate-time-use=0.5 has a 69% chance of being > 0 ELO than 1.0
If we set immediate-time-use to be less than 1, we just have to be a bit careful with how that works in situations where people were complaining about leela not using enough time (ponder, gpu temp bugs, etc). I think with immediate-time-use=1, the TM would be more robust to those situations.

**Comment by roy7** [comment]
Also keep in mind when the increment amount is very small, immediate time use can't do anything once the main time has expired. Because there's a minimum time before it is allowed to move quickly each move to calculate the nps.

**Comment by roy7** [comment]
I do prefer 1 myself, I wonder if eventually we can clop larger increment time or pondering.

**Comment by jjoshua2** [comment]
Some ponder on tests would be good. I very much like that slow_mover/scale is at 1.0 so I would not like that to change. The immediate % and the curve parameters should be enough to not need this. The only exception would be for ponder on. SF has a slowmover *= 1.5 logic if ponder==on.

Francis is tuning TM curve (with some code rewrite) so too much duplicate work there should be avoided.

You tested `Aversion to search if change unlikely` before, but I think maybe it was invalid? I think this is a great candidate since its likely to be changed with all of the other things changed recently (mostly the immediate %). Also the last CLOP i did had a higher value than we are using, so even if it is the same it could be an elo gain to restore that possibly.

**Comment by jjoshua2** [comment]
20ms is quite fast. I wouldn't worry about trying to make that work. But if 100ms doesn't work at defaults that is disconcerting.

I agree that as it sounds now probably something like 1.5 for slowmover is likely a small improvement (since immediate time use is not 1.0, and time curve was tuned at 0.0), but I think the time curve could be retuned instead to use more time up front which will have mostly the same effect as increasing slowmover, without needing an extra parameter to be tuned. Maybe it would lose 2 elo but realistically tuning 4 parameters or so has much bigger elo noise than that.

**Comment by fli** [comment]
Did/can you test ponder with `Fraction of saved time to use immediately = 1`? I can imagine if it is 0.6 then the extra time will tend to accumulate rather than being used, since pondering will increase the amount of smart pruning and cut off moves earlier.

**Comment by zz4032** [comment]
If `Fraction of saved time to use immediately` and pruning (controlled by `Aversion to search if change unlikely`, correct?) interact so much with `Scale thinking time`, they should be tuned altogether simultaneously at some time in the future. Such a tuning would require longer time control and need a lot of games. I think that should be done once all the TM curve changes are implemented as @jjoshua2 mentioned.
For a quick test I can retune `Scale thinking time` with `Fraction of saved time to use immediately = 1` and ponder=on.

**Comment by roy7** [comment]
Immediate time usage set to 1 would remove any need for slow move since there is no saved time bleeding into the rest of the match. All bonus time used asap all game long. With immediate time use 1, if the curve isn't what we want, then the curve needs adjusted. Slowmover is just a hack to use bonus time earlier in a non dynamic way.

I think @Francis solution to remove existing time curve settings is quite nice.

**Comment by zz4032** [comment]
Actually this is an "issue" tagged with "release blocker" waiting for input for better settings for v0.18. Not a discussion about what is currently in long-term development. If a parameter value was found providing better performance, it should be tested and implemented in v0.18 as far as I understand. If it's too late for v0.18 to change parameters, the issue needs to be closed.
There is still `Aversion to search if change unlikely` and `Scale thinking time` with ponder=on to tune. Any chance any value updates will make it into v0.18?

**Comment by fli** [comment]
Just FYI and warning regarding CLOP. I just ran CLOP overnight for 1500 games and then realised that my parameter names were wrong and the values in lc0 weren't being changed, yet half of the parameter space was faded in CLOP. So I think we definitely need to check whether tuned parameters are stronger (run direct tests until 95% confidence of superiority?) before adding them to release, and be careful making assertions based on how the CLOP graph is faded.

**Comment by zz4032** [comment]
I agree we need more testing, other testers could help out here.
Yes, it's easy to set up something wrong in CLOP with no warning from log files. I'm rechecking all settings several times...
Faded sample areas are telling me there is a pronounced sample areas with much higher performance. So there should a higher Elo gain (if the standard value is much different from the tuned). Didn't know there could be some fading with equal performance throughout the complete range.

Meanwhile I finshed tuning Slowmover with ponder=off.
382 games.
Tuned parameters:
`Scale thinking time -> 1.71 (standard: 1.0)`

Tuning:
![plot](https://user-images.githubusercontent.com/11909324/46244094-54ee7280-c3da-11e8-93e3-beaf3cce45f2.png)
CLOP diagram:
![clop](https://user-images.githubusercontent.com/11909324/46244098-5a4bbd00-c3da-11e8-98de-686335e92cb2.png)

**Comment by jjoshua2** [comment]
I don't think there can be such obvious fading like in that last picture
and still have equal elo throughout the range. When it's that extreme you
know the parameter is doing something and the CLOP algorithm is working.
When there is the bug where the parameter doesn't do anything, all the
range is tested evenly, and not just a band.

**Comment by fli** [comment]
That was my intuition too. It was fading before I went to sleep which is why I didn't think anything was wrong and left it running. But when I checked it again in the morning the top right quadrant was all significantly faded. I'd upload the .dat file but it's already gone.

**Comment by jjoshua2** [comment]
Yes, I can see that happening, but there is a difference between a corner
faded and getting an actual ellipse, like you should get when you tune two
variables.

**Comment by zz4032** [comment]
How do you want to proceed with TM curve parameters? As Slowmover tuning shows, current TM curve is far from optimal.
