### ISSUE TITLE
Build failing on 32-bit architectures because of the assert: sizeof(Node) == 64

### ISSUE THREAD

**Issue by lealgo** [LeelaChessZero/lc0#369]
this is the commit:

https://github.com/LeelaChessZero/lc0/commit/f35e1289bb268b3ec4f619b3311967304264e29c

_Originally posted by @lealgo in https://github.com/LeelaChessZero/lc0/commit_comment/create#commitcomment-30569214_

**Comment by lealgo** [comment]
Could it be replaced by the sum of the sizeof of Node's members?

**Comment by domschl** [comment]
`sizeof(lczero::Node)` is 40 bytes on 32-bit systems (e.g. Raspberry), and not 64 bytes as on 64-bit systems.

The `static_assert(sizeof(Node) == 64` therefore breaks 32-bit builds:
https://github.com/LeelaChessZero/lc0/commit/f35e1289bb268b3ec4f619b3311967304264e29c#diff-0a9d1f9ad753d72c16c057666bb3533eR257

@dubslow : please consider removing the assert, 32-bit builds work just fine otherwise.

**Comment by domschl** [comment]
PR #373 uses two `#ifdef` for specific exceptions to 'standard' 64-bit compile.
I've checked with Raspberry PI ARMv7 and Linux 64bit.

**Comment by borg323** [comment]
This should be fixed now - I've tested this on win32, can someone confirm on arm?

**Comment by ScallyBag** [comment]
Yes, works fine now on my RAspberry Pi

Al

**Comment by borg323** [comment]
Perfect, closing.

**Comment by lealgo** [comment]
good, working for me on armv6l too. thanks!
