### ISSUE TITLE
lC0 v18.0 crash

### ISSUE THREAD

**Issue by AlingoAlingo** [LeelaChessZero/lc0#398]
![img_20180929_115501](https://user-images.githubusercontent.com/33194033/46243699-ab11e480-c3df-11e8-8528-ec1b4146439a.jpg)

**Comment by borg323** [comment]
Can you give a few more details? both system details, line CPU, GPU, memory, vram etc. and lc0 configuration.

**Comment by AlingoAlingo** [comment]
![img_20180929_155400](https://user-images.githubusercontent.com/33194033/46246030-62b6ee80-c400-11e8-9011-7067319ba681.jpg)
![img_20180929_155414](https://user-images.githubusercontent.com/33194033/46246031-634f8500-c400-11e8-81e7-eb74547ba467.jpg)
![img_20180929_155425](https://user-images.githubusercontent.com/33194033/46246032-634f8500-c400-11e8-8dc0-b30e5330bc1e.jpg)
![img_20180929_155434](https://user-images.githubusercontent.com/33194033/46246033-634f8500-c400-11e8-8d68-64a037981cca.jpg)
![img_20180929_155444](https://user-images.githubusercontent.com/33194033/46246034-634f8500-c400-11e8-8be5-adf5f49affdf.jpg)
![img_20180929_155451](https://user-images.githubusercontent.com/33194033/46246035-634f8500-c400-11e8-9915-aa1da55f5b52.jpg)
![img_20180929_155458](https://user-images.githubusercontent.com/33194033/46246036-63e81b80-c400-11e8-98a2-ebff9a39b50b.jpg)
![img_20180929_155507](https://user-images.githubusercontent.com/33194033/46246037-63e81b80-c400-11e8-9e0f-d866ed4532f2.jpg)
lco config. is default

**Comment by borg323** [comment]
Looks like you are using the opencl backend. You can try to reduce the backend batch size: There should be a configuration option `NN backend parameters`, where you can write `batch_size=1` and if this works increase it, maybe the default of 16 is too much for this gpu.

**Comment by all12** [comment]
I'm using a ssd.
OpenCL

batch_size=1 or 2 or 3 or 4 or 5 or 16 or 32 doesn't helped.


First bug: 
I have ddr3 16 gb and there is definetly a memory bug.
-This happens very rarely and not every game but it happens.


Second bug: 
It crashes like you can see AlingoAlingos first picture.
-This happens nearly every game when using the fritz 15 or fritz 16 gui or the chessbase 12 or 13 or 14 gui.
-**It happens while running infinite analysis and also when playing vs other engines**.
-Between the first half move an before mate. Sometimes after 20 moves, sometimes after 50 moves, sometimes even after 186 moves.
-But sometimes LC0 is able the draw by 3-fold rep or to win very fast, so the game ends normal before this bug can work.


Third bug: 
It stops calculating, without a bug information window.
-This happens nearly every game when using chessok aquarium 2016, 2017 or 2018 gui.
-You only see the white window where LC0 was calculating before. In the other white window you can see the opponent which is calculating like always.
-It doesn't matter if this is ponder on or not.
-**It happens only in matches and tournaments. And never happens when doing infinite analysis**.
-Between the first half move an before mate. Sometimes after 20 moves, sometimes after 50 moves, sometimes even after 186 moves.
-But sometimes LC0 is able the draw by 3-fold rep or to win very fast, so the game ends normal before this bug can work.


Fourth bug:
It freeze the chess aquarium 2016, 2017 or 2018 gui.
-This happens only when you start a match or tournament.
-In the first ~30 seconds you can click the gui and you can also click the buttons of the gui like always but if you are doing this later, then the gui will freeze.


The old v.0.10.0 was without these bugs.

**Comment by AlingoAlingo** [comment]
The old v.0.10.0 It works perfectly without crash

**Comment by oscardssmith** [comment]
Have you tried 17.0? 10.0 is a pretty old version at this point.

**Comment by AlingoAlingo** [comment]
I tried 16.0 , 17.0 exactly the same problem crash in the same way

**Comment by all12** [comment]
I tried 16.0, 17.0, 18.0 and also the rc1 and rc2 versions.
Same problems.

**Comment by oscardssmith** [comment]
In that case, you should probably just go on the help discord channel rather than posting an issue. https://discord.gg/tjeZZ7

**Comment by cwbriscoe** [comment]
It would help to see the command line output.  Open up a dos window, go to the directory where lc0.exe is installed and then run lc0.exe.  after that type `go nodes 1`.  Print what is displayed here.

**Comment by all12** [comment]
@AlingoAlingo has discord helped you?

**Comment by AlingoAlingo** [comment]
no lc0 18.0 does not work for me

**Comment by mooskagh** [comment]
@AlingoAlingo please come to #help channel of discord to get help, and please don't create new issues regarding your crash here.

**Comment by JamieO53** [comment]
The link has expired. Go to [Discord#Help](https://discord.gg/EA6r5rG)
