### ISSUE TITLE
Pack more than one game per training games files

### ISSUE THREAD

**Issue by ASilver** [LeelaChessZero/lc0#55]
While building NNs, one significant issue is that each training game is gzipped into a single file. That means that 1 million training games to build an NN means 1 million files in the same folder. That is _incredibly_ impractical. I would request this be changed to either 1000 or 10,000 games per file.

**Comment by Tilps** [comment]
I think this is a server/training issue, rather than an lc0 issue.  Although maybe lc0 could support game upload batching, its batch size would probably be *much* smaller than 1000 to keep latency of game feeding to the server down.

From a training perspective the current one game per file is a significant part in getting close to properly randomizing the order positions are processed in as it allows us to easily shuffle at the file level before feeding into the per-position shuffler.  It has lots of downsides too, but unless we came up with a good story for randomization, I think that would block increasing the games per file above one.
If we can solve that issue, I think 1000 sounds about right.

**Comment by oscardssmith** [comment]
Any updates on this? This would also probably reduce disk space used as compression works much better on bigger files.

**Comment by mooskagh** [comment]
I don't think that's feasible to do in engine. We can indeed think about repacking it for archive purposes on server side. The training game is sent as soon as it's ready, so disk space on client side is not an issue.
As training needs to open training games in random order, keeping them in one archive even on server is inconvenient.

In any case, it's not something to do in engine side, so closing.
