### ISSUE TITLE
The non-monotonic nature of `info depth` output confuses polyglot

### ISSUE THREAD

**Issue by borg323** [LeelaChessZero/lc0#571]
Edited polyglot log excerpt:
```
Engine->Adapter: info depth 12 ...
parse info 11 11
Adapter->GUI: 12 ...
Engine->Adapter: info depth 11 ...
parse info 12 12
killed because of small depth 11 < 12
```
The `info` is not send to the gui until the next `info` which shows depth 12:
```
Engine->Adapter: info depth 12 ...
parse info 11 12
Adapter->GUI: 12 ...
```
I have seen sequences of several consecutive `killed because of small depth` messages, and reports of several minutes of no `info` display that may be attributed to this.

**Comment by GBeauregard** [comment]
Note when Stockfish ran into a similar problem when they introduced a patch that prevented the depth from monotonically increasing (see https://github.com/official-stockfish/Stockfish/issues/1787 for issue).

Stockfish's solution was to change their reported depth to be monotonically increasing in order to avoid confusing GUIs (see https://github.com/official-stockfish/Stockfish/commit/3f1eb85a1ceb1b408f8f51cb82064b69e095399d for the fix).

It's probably worth reworking our reported depth as well so it's guaranteed to be monotonically increasing and won't interfere with any GUIs.

**Comment by GBeauregard** [comment]
Here's an example of a 20 minute pause in output this can cause

![image](https://user-images.githubusercontent.com/1444900/49692118-74afbe80-fb20-11e8-9216-45d17e071a40.png)

**Comment by Videodr0me** [comment]
There was some discussion about this before implementing depth. Some people said that SF also has non-monotonic depth and that it is no problem. Now it seems SF changed back to a monotonic depth increase. We can easily also do that, i think its only a trivial change. We can basicaly maintain an internal depth (which can also be decreasing), but only output if last depth > previous depth.

The only argument for a non-monotonic depth is that it more accurately depicts leelas though process - for example when suddenly finding a refutation in a deep main line and then going wide. But i think thats so sublte that we can easily do without. Any other thoughts?

**Comment by Naphthalin** [comment]
Is this still an issue? If yes, which GUIs can't deal with that?

**Comment by mooskagh** [comment]
Not an issue, bug in polyglot. :-P
