### ISSUE TITLE
[feature-request] Linux builds for x86_64

### ISSUE THREAD

**Issue by Technologov** [LeelaChessZero/lc0#662]
Please provide statically-linked Linux binary builds for x86_64 (and maybe for x86-32 and ARM, if time permits).
For 3 targets: CPU (SSSE3), OpenCL and CUDA.

Thanks in advance
-"Technologov"

**Comment by putztzu** [comment]
FYI - I just submitted a Pull Request with a script that makes it possible to easily build lc0 with an OpenBLAS backend on any x64 machine, physical or virtual. Can be easily modified to install on x586 (32-bit) running openSUSE Tumbleweed (but untested). Until the Pull Request is approved, you can view on my github lc0 site

https://github.com/putztzu/lc0/blob/putztzu-patch-1/openSUSE_install.md

**Comment by putztzu** [comment]
Final Pull Request waiting for approval at the following link for installing openSUSE on any x64 machine, physical or virtual..
Note that the script can easily be modified to support compiling for other distros, and I welcome anyone who wishes to do so to simply clone my repo, make your modifications and submit a Pull  Request to me.
And, since the openSUSE RPMs are built on the Open Build Service, creating packages for other distros (RPM and DEB) and distro versions usually requires only a few clicks.

https://github.com/putztzu/lc0/blob/master/openSUSE_install.md

**Comment by Arapoon** [comment]
Hi guys !

I tried to compile LC0 with Kubuntu but failed.
I gave all informations here (in french) https://forum.p2pfr.com/sutra148074.html#148074

I have some friends who also failed in compiling this programm.

Is it really to hard for you to make some builds ready to use for debian/ubuntu users ?


Thx a lot

**Comment by oscardssmith** [comment]
If you ask in the lc0 discord, we can get people set up pretty quickly. A fair number of the devs use ubuntu, so it won't be too hard. We really should get an shell script for ubuntu that does it. I assume it wouldn't be too hard.

**Comment by Naphthalin** [comment]
As linux binaries seem to need the specific combination of cuda-version and other libraries, this doesn't seem feasible. Is the current build script still too hard to use?

**Comment by Technologov** [comment]
current script is prone to failure on non standard compilers and OSes
(fails on Ubuntu 16.04 and 20.04 with stock compilers).

чт, 30 квіт. 2020, 17:05 користувач Naphthalin <notifications@github.com>
пише:

**Comment by mooskagh** [comment]
As described above, it's not feasible to have pre-built binaries.

However, there should be working build instructions for all popular linux distributions.
Please file and issue (or update docs yourself) if https://github.com/LeelaChessZero/lc0/blob/master/README.md#building-and-running-lc0 doesn't work for you.
