### ISSUE TITLE
Problems compiling Leela engine for CUDA

### ISSUE THREAD

**Issue by Technologov** [LeelaChessZero/lc0#663]
Platform: Ubuntu LTS 18.04 x64

```
apt-get install -y clang-6.0 ninja-build pkg-config protobuf-compiler libprotobuf-dev meson libopenblas-dev ocl-icd-opencl-dev
git clone -b release/0.20 --recurse-submodules https://github.com/LeelaChessZero/lc0.git
cd lc0/
./build.sh

```
But in the end I got a version for OpenCL, rather than CUDA.
I'm not sure if I have installed NVIDIA CudaNN properly, as I had problems with it.
How do I force Leela to compile for CUDA anyway ?

On NVIDIA GeForce GTX 1080, I am getting ~2000 nps only (ID 32400) via OpenCL.
I was able to compile for CPU also (OpenBLAS) on another host... but the binary ended up non-portable to older PCs (without AVX2 CPU), when moving binary from Haswell to Sandy Bridge.

--- alternatively -- please consider providing binary builds for Linux x64, as it will solve a lot of problems for many users alike.

-"Technologov"

**Comment by Naphthalin** [comment]
>  How do I force Leela to compile for CUDA anyway ?

the build script needs the correct CUDA and cudnn versions to build the binary, either as the default versions or specifying the paths to it. 

`./build.sh -Dopencl=false -Dgtest=false -Dblas=false --default-library=static -Dcudnn_include=.../cuda100/include -Dcudnn_libdirs=.../cuda100/lib64` is the command I use for building on Ubuntu.

this specific issue seems to be outdated though since the switch to C++17, and the discussion about providing linux binaries is in #662.
