### ISSUE TITLE
2 million inflight visits, node ends with very low Q value

### ISSUE THREAD

**Issue by killerducky** [LeelaChessZero/lc0#680]
`0114 20:32:22.544094 244 c:\projects\lc0\src\mcts\search.cc:292] d2e2  (282 ) N: 1972264 (+2447326) (P: 16.19%) (Q: -0.99911) (U: 0.00063) (Q+U: -0.99848) (V: -0.2401)`

See lc0log.txt attached.
[lc0log.txt](https://github.com/LeelaChessZero/lc0/files/2757853/lc0log.txt)

Doesn't seem to happen if I remove --no-out-of-order-eval.

**Comment by Tilps** [comment]
I think this is evidence that terminal multi-visits + no-out-of-order can be really really bad.

**Comment by ddobbelaere** [comment]
Just pointing out that there's nothing wrong with the Q value (it's actually very high, close to 1 instead of -1). The line shown above from @killerducky is from the ponder information.

I was able to reproduce the issue. See logfile here: 
[lc0log.txt](https://github.com/LeelaChessZero/lc0/files/2772632/lc0log.txt)

This is the starting position:

![screenshot_20190118_114124](https://user-images.githubusercontent.com/38748663/51382049-0ba36980-1b16-11e9-90ce-3c8723e679a4.png)


Funnily enough, the move I get with approximately 2 million visits is Qf2 (instead of @killerducky's Re2, but it's a different net though). Stepping through the search tree reveals that (after a few blunders) we walk into a mate (see https://lichess.org/P0GtMcQr if you're interested).

**Comment by ddobbelaere** [comment]
I forgot to say that the issue doesn't occur with out-of-order eval enabled, just as @killerducky observed.

**Comment by killerducky** [comment]
I think #680 is supposed to fix this.
