### ISSUE TITLE
Cpuct is half of that in AlphaZero's paper?

### ISSUE THREAD

**Issue by jizhongling** [LeelaChessZero/lc0#694]
In this blog http://blog.lczero.org/2018/12/alphazero-paper-and-lc0-v0191.html, it said that "Action space turned out to be 0..1, not -1..1". Since AlphaZero used Cpuct=2.4, Leela's Cpuct=3 means it is almost half of AlphaZero's Cpuct, due to twice of action space. Even though Leela has CpuctFactor=2, but from the code in function ComputeCpuct() in mcts/search.cc:
return init + (k ? k * FastLog((N + base) / base) : 0.0f);
We see that init=Cpuct is not multiplied by k=CpuctFactor=2, which means Cpuct_init is half of that in AlphaZero's paper.

This means that Cpuct=5 should be the correct choice. Though in blog http://blog.lczero.org/2019/01/leela-in-december.html, it said that Cpuct=5 is too large, I tried Cpuct=4.5 is much better than Cpuct=3, especially for avoiding lose to Stockfish.

I think we should anyhow consider larger Cpuct, or explain why we still use the same Cpuct even for twice action space.

**Comment by ddobbelaere** [comment]
The pseudocode at http://science.sciencemag.org/highwire/filestream/719481/field_highwire_adjunct_files/1/aar6404_DataS1.zip says 1.25 for training, which is the value we are using for training (or more precisely, twice this value, namely 2.5).

For matchplay we default to 3, probably because this gives the best results for our 256x20b nets (although this value probably has to be tuned again for the SE nets). See also #567. So, in conclusion, it also depends on the net.

**Comment by jizhongling** [comment]
Thanks for the explanation. I see the reason. And Cpuct=2.5 lowers down the nps as you said and in blog http://blog.lczero.org/2018/12/alphazero-paper-and-lc0-v0191.html
