### ISSUE TITLE
Training game PGN bug

### ISSUE THREAD

**Issue by thejhonnyguy** [LeelaChessZero/lc0#75]
Summary: Some training games PGNs are wrong.

Example found here: http://testserver.lczero.org/game/5311612

Reproducible? With luck, I suppose.

**Comment by Tilps** [comment]
This is not an lc0 bug, its a client bug.  But there the bug is not in the lczero-client repo, its a bug in notnil/chess - which Tilps/chess inherited when forked.

I've updated Tilps/chess to remove the offending e.p. output - and raised an issue against notnil/chess to hopefully get it fixed there some day.

So this should be fixed when users recompile their lc0 client.
