### ISSUE TITLE
When RAM limit is reached, start deleting old nodes

### ISSUE THREAD

**Issue by koedem** [LeelaChessZero/lc0#823]
Currently when RAM limit is reached by Leela she just stops calculating. What if she instead started deleting old nodes to make room for new ones. (the disadvantage of course being if we need those old nodes again we have to recalculate them) The hope being that many old nodes might not be needed anymore. Not sure how well this would work in practice but worth a try IMO.

**Comment by Hersmunch** [comment]
Note that this has been done over in the Go implementation. See https://github.com/leela-zero/leela-zero/pull/1082 & https://github.com/leela-zero/leela-zero/pull/1134.

**Comment by MelleKoning** [comment]
@koedem Can you explain what you mean by 'stops calculating'? 

Deleting old nodes is actually handled; every time a new node is added to the cache, the oldest node gets deleted. See https://github.com/LeelaChessZero/lc0/blob/master/src/utils/cache.h#L75

**Comment by koedem** [comment]
@MelleKoning I am not talking about the NN cache, I am talking about the search tree.

**Comment by Naphthalin** [comment]
Did you ever try this? I think with our current code logic, this would be a very bad idea, and most nodes will actually be still needed at some point as children of other nodes.

**Comment by koedem** [comment]
At least I did not ever try this. Instead I got a SSD as swap space and nets are bigger these days too. (so fewer nodes)

Though it might still be worth for some people. Some nodes will be used again and have to be recalculated but some refuted lines might not ever be used again. (and it can't be worse than just stopping to calculate I'd argue)
But probably not worth the effort trying to implement this.

**Comment by mooskagh** [comment]
In Leela Zero go, as far as I know, there is no edge and node separation, so trimming low policy nodes with no visits makes sense there.

We have edges separate from nodes, and edges are very lightweight relative to nodes, and nodes are only created during the first visit. So this easy solution is not possible.

While offloading/trimming nodes is a useful thing to have, it requires redesign of node storage rather than a simple feature to add. Therefore I'm closing this for now.
