### ISSUE TITLE
Depth tracking needs re-design and re-implementation

### ISSUE THREAD

**Issue by dubslow** [LeelaChessZero/lc0#86]
The current `depth` output is totally useless for people and protocol alike, since it never goes above 2, ever.

PR #74 would address that particular issue, replacing the current depth with something that's approximately right, and at least somewhat useful, but it isn't necessarily ideal.

So, even if/when 74 is merged, we need a better design for depth. Doing a logarithmic approximation with calculated branching factor is considered suboptimal; perhaps better is a linear average of the depth of all nodes. There are other choices as well.

And, even aside from design choices and issues, the current implementations, either of them, suffer the drawback of using storage inside the `Node` structure, which is a precious resource per issue #13. No matter which design is chosen, it should not require any storage inside each `Node`. This shouldn't be too hard; it should be relatively straightforward to maintain a variable or two at the top level `Search` , which is updated during node eval backpropagation. This would be effective with the caveat that it is stateful: tree reuse would require complete recursive calculation of the top level variables for the subtree in question. (One potential workaround is to have `Search` do a different depth calculation for each potential first and second ply move; then, when the tree is pruned for these two moves, we already have the requisite calculation done, and save the full recursive recalculation only for more extreme (i.e. rarer) tree pruning scenarios.)

**Comment by mooskagh** [comment]
I do have some ideas to share, but let's address issues that are blocking for lc0 launch for training first.

**Comment by Videodr0me** [comment]
Just a couple of thoughts for whenever this gets any priority (obviously not now):
1) I would propose  moving depth calculation to picknode instead of backpropagation. Mainly because in backpropagation we never know during traversel of the tree upwards what depth we are really in until we reach root. This makes the info not really usable for any (future) backpropagaton schemes (e.g. depth depending formulas). While in PickNode we traverse top down so depth at any level has actual meaning and can be used (in the future) for deciding which node to expand (depth dependend PUCT).

2) Full depth in my opinion is not needed at all. It does not convey any useful info (even in long searches  over hours hardly ever reaches 4 - 5) and it does have excessive overhead as in the backpropagation traversal on every levels all nodes are checked. Also in contrast to a/b engines full depth does not gurantee that a tactic within those moves is really found (it might take a while for visits to catch up, even if Q is already properly backpropagated)

3) Max depth is useful and should be used for what traditional engines call selective depth (as it is currently the case)

4) Normal depth should be between 1 and max depth and increase monotonically. An averaging scheme should therefore make sure avg new > avg old, otherwise due to the nature of MCTS avg. depth can also decrease if a part of the tree is heavily visited that has not been explored before. While i would love to see the faces of users when suddenly depth decreases, its probably too shocking.

5) Any formula which ensures 4 is fine with me, be it log, some avg. or whatever. With traditional engines you depth roughly increases by one for a doubling of time (or 1.7x which is near the effective branching factor). Also rather than node count, one might think about using NN evals as this is more constant per time and not affected by caching, hitting terminal nodes etc.

**Comment by dubslow** [comment]
74 more or less satisfies 4 -- in my testing on slowass cpu, it can occasionally flicker between two depths, but I consider this a feature rather than a bug -- MCTS *isn't* monotonic in depth, and so restricting the UCI output to be so when the underlying data isn't is a bit silly IMO. But then, at the end of the day/on average, it is *generally* monotonic, and even though I saw occasional flickers on my CPU, I suspect that on a GPU the nps/uci output frequency ratio is high enough that the flickers would be washed over anyways.

So, until such time as this issue gets the attention it requires, 74 should be merged immediately in order to deal with what you call issue number 2, namely that the current depth is completely and totally useless.

**Comment by Videodr0me** [comment]
@Dubslow You do not have to convice me - it would make leela unique in a new way. I have nothing against it, but maybe some guis don't play nice. Maybe adding a new avg > old avg check? But apart from that i totally agree.

**Comment by dubslow** [comment]
I don't think it will be a problem.

**Comment by mooskagh** [comment]
As for 4, if the only problem is shocking users, that's totally fine.
But I think it will also shock some GUIs. At least I noticed that some GUIs (including cutechess) update the last line on the screen if depth is not changes, and creates a few one if it does. Not sure how it will behave if depth starts to decrement.

Saying all that, I don't agree that #74 have much meaning.

**Comment by dubslow** [comment]
cutechess works fine with depth decrements.

74 has way more meaning than current output.

**Comment by dubslow** [comment]
Okay, independent of Edge-Node separation, memory use, implementation, or anything else, I require one big behavior criterion to be met by any depth implementation for me to support it: the depth output *must* be solely a function of Leela's move analysis, which is to say, an identical move analysis must produce an identical depth when created twice.

So what do I mean by move analysis? I mean the grand sum of data, information, and estimation that Leela uses to select a move. That, in turn, means the information in all nodes in the searchtree: Leela's  "move analysis" is tantamount to generating a node tree, whose information is propagated to the root node by the rules of MCTS. Leela's move analysis, everything that decides the move and nothing that doesn't, *is* the node tree.

That in turn means that my rule can be restated as "an identical node tree must produce an identical depth in all circumstances". That is important because the *how* a tree was produced varies, thanks to tree reuse. My rule is that an identical node tree must produce an identical depth, no matter how many separate searches were used to generate the node tree, and no matter in which order the node tree was searched (since MCTS is also order-independent). In particular, this excludes "most recent n nodes" type depths, since those obviously can be wildly different for a given identical node tree, since it depends on search order.
