### ISSUE TITLE
Time Management Issue

### ISSUE THREAD

**Issue by TesseractA** [LeelaChessZero/lc0#869]
https://cd.tcecbeta.club/archive.html?season=15&div=champions&game=29

At TCEC, Most basically, Leela lost to Houdini 3 when she was +1.28 from the initial book position.

This game, Leela went from +3 to +12 in one move. If Leela does that and doesn't spend more time on the move, she will give up too early. It is unreasonable if Leela is such a good engine for her to spend so little time on one move when its clear that she has or is missing something. I'm going to write a TM patch for things like this if I can. There needs to be a gradient that encourages Leela to spend more time on moves that show large deltas between positions. If anyone else can do it before me and/or do it better than I (i'm relatively new to this) then please-- indulge yourself.

I noticed a similar issue with Allie when Allie played KMCTS at the Computer Chess Championship.

**Comment by borg323** [comment]
Lets take this opportunity to do it right. The idea behind the current time management is described in <https://github.com/LeelaChessZero/lc0/pull/271> with a small refinement in <https://github.com/LeelaChessZero/lc0/pull/634>. The basic idea is that we try to predict how many moves are remaining in the game and divide the remaining time by this estimate to allocate time for the next move. (There is also the accumulated time from smart pruning that complicates things, but I'll ignore it for now). There are two problems with this approach:
1. The estimation is only taking into account the current move number and not the score. I expect we have enough data by now to derive a correction term based on the current Q.
2. The more serious issue is the simple division used to calculate the time allocated to the current move. The estimation parameters were optimized to improve Elo, resulting in a formula that is no longer a good predictor of the moves remaining. **I think the first step towards resolving such issues is to separate the remaining move estimator from the move time calculation: A new move time formula is needed** (taking the remaining moves as input) **that is tuned separately to maximize Elo.** This formula can take as additional inputs the current Q and the delta to the previous one to allocate more time when needed. (I expect this will also help a bit when playing without increment.)
3. The actual issue discussed in the first comment is probably best addressed in the smart pruning code (which is orthogonal to the above). It seems to me the best way to handle it is by a temporary reduction of the smart pruning factor to 1 (or even less) where needed.

**Comment by mooskagh** [comment]
Fyi I'm currently refactoring time management code for it to be able to dynamically decide what time is, so it's better to wait with any changes other than simple formula tuning.

**Comment by mooskagh** [comment]
In addition to per move time budget estimation (where Lc0 basically dumps all remaining time between moves 50 and 60), I think there are 3 issues that we noticed and that has to be fixed:

1. Too short think when reused tree is too small (during the first moves or when opponent made unexpected move). Probably can be solved by having target bestmove nodes rather than target time budget.

2. Wasting all the time when picking between transpositions.
I don't know how to fix that nicely, but we can use something hacky like looking at cache hit rate and reduce budget (or smart pruning factor) when it's too large.

3. Too long think on obvious moves.
This is minor and there are obvious ideas how to fix it (e.g. by looking at N and Q of two top moves).

**Comment by borg323** [comment]
>     3. Too long think on obvious moves.
This is probably due to large savings from smart pruning and the high default value of `ImmediateTimeUse`.

**Comment by Ipmanchess** [comment]
Thank you guys for looking into TM ..it's very important!
When you analyse my data i have in my spreadsheet from my tests you could learn a lot how engines act with there time and against which opponents.
I'm pushing always for these endgame fixes as it has a connection with your time left..therefore i was hoping to see endgame fixed first them TM would be my next annoying pushing thing ;)
But these are the two first things that need to be improved so that Lc0 can progress in the right way!

For sure any PR that will come out about TM and need a test..let me know ..i'm will follow this PR closely..
When you try something just check it with Sudden Death games..you know directly if your TM is good or not! (Will be difficult so long endgame is not right)

Ipman.

**Comment by jjoshua2** [comment]
I think piece count may be a better measure of complexity than just Q.
Because a +2 opening needs a lot more time for the rest of the game than
a +2 endgame does. There needs to be some measure of complexity until we
get a complexity output which would be hard to train.

**Comment by oscardssmith** [comment]
@jjosh reopen plz. You accidentally hit close.

**Comment by mooskagh** [comment]
Budgetting time for move (in average) and detecting when to (almost) instamove (due to having only one good move) are totally ortogonal.

For the first I think it's indeed the best just to gather stats of average "moves till game end, provided game is not ended" for every number of pieces on board between 3 and 32 (but none of 3 list items that I wrote touched base time budgetting, they touched more like exceptions).

For the second, we have to look at N and Q or so something similar.

**Comment by oscardssmith** [comment]
Should we tweak the TM depending on which TB's are loaded? Presumably if we have 6 man TB, we can use all our time sooner, and coast off of TB once we reach it.

**Comment by jjoshua2** [comment]
The TM was already tuned with 6 man syzygy mostly. We can't really afford
to tune two many things since it takes thousand games easily. I think  a
tune with 6 man and with none could be done an interpolate between though,
for a 3 elo gain :)

**Comment by borg323** [comment]
Simple (untested) idea towards addressing my point 2 above: Adjust `TimeMidpointMove` and `TimeSteepness` to approximate the distribution of moves remaining. Looking at TCEC season 15 superfinal, the midpoint should be about 80. This will give less time per move, but `Slowmover` can be used to offset this.
Correction terms can then be added, either for more accurate moves remaining estimation, or for better time allocation.

**Comment by RollYrOwn** [comment]
Is there any realistic method for a zero approach here?

**Comment by oscardssmith** [comment]
TM isn't supposed to be zero. The definition of Zero that we follow (as given by A0) is strictly about how the NN is trained, not how we use it.

**Comment by jjoshua2** [comment]
I would be all for a zero based one if we had a training target of how much
time is optimal to spend for each move! Best we could do is complexity
and/or accuracy which could be good.

**Comment by borg323** [comment]
I processed the pgn from <https://discordapp.com/channels/425419482568196106/530486338236055583/608596242024366081> to recalculate the moves per game, in order to get a set of parameters for the log-logistic distribution we use for the moves remaining estimation. This gives a set of:
-`time-midpoint-move=82.21` and 
-`time-steepness=3.77`. 
Using this set would require an increase to `slowmover` in order to give more time to earlier moves. I guesstimate the value for `slowmover` at around 1.5 if anyone is interested to check this.

**Comment by borg323** [comment]
Using a larger data set, I get the following:
`--time-midpoint-move=72.75` and
`--time-steepness=3`.
The pdf for the game ply distribution with this is
![pdf](https://user-images.githubusercontent.com/39573933/63104190-285a2f80-bf87-11e9-8feb-10f01721c3aa.png)
and the correspondng cdf is
![cdf](https://user-images.githubusercontent.com/39573933/63104214-34de8800-bf87-11e9-9906-043c6f9c39f3.png)
In both figures red is the fitted curve and blue the actual data used for the fitting.
With these parameters, the remaining moves estimator should be pretty accurate, but leaves only `--slowmover`, `--move-overhead` and `--immediate-time-use` to tune the time allocation.

**Comment by borg323** [comment]
It turns out that @Ipmanchess has already experimented with this, and found that `--time-steepness` of 2.5 or 4 (depending on tc) was good for playing without increment, not running out of time. I have plotted the pdf of these settings (black curves) together with the default setting (green), and obviously both are better estimators, in particular in the tail end that is more important to avoid time forfeits:
![pdf2](https://user-images.githubusercontent.com/39573933/63176282-53f41d00-c04e-11e9-9642-f2d6e6441a58.png)

**Comment by borg323** [comment]
With a lot of help from @kiudee, we tried to optimize `--slowmover`, `--smart-pruning-factor` and `--immediate-time-use` but the results were very specific to the machine and TC used. However they seemed to hint that `--slowmover=2.0` seemed like a good choice. Fixing this I did a clop run that converged to  `--smart-pruning-factor=1.56724` and `--immediate-time-use=0.537672`. @kiudee was kind enough to post process the clop .dat file using his algorithm, which suggested a slightly different point and made a cool figure:
![sm_2_with_inc_2](https://user-images.githubusercontent.com/39573933/64733853-2c2d9300-d4ee-11e9-9dc3-a17c96aa5972.png)
Testing with different time controls hints that this is probably a better set of parameters for performance similar or better to master with several different TCs, and no losses on time with no increment. If anyone is interested to try this, the full set of parameters is:
`--time-midpoint-move=72.75`
`--time-steepness=3`
`--slowmover=2.0`
`--smart-pruning-factor=1.65`
`--immediate-time-use=0.58`

**Comment by Naphthalin** [comment]
Is this solved by the new time management which tries to have the tree size approximately the same, or do we have to assume that the issue described here isn't (weakly) solved by the change?

**Comment by borg323** [comment]
Hopefully it is, but too early to tell for sure.

**Comment by TesseractA** [comment]
Is this a closable issue? I've noticed time management has greatly improved since our original tries, unless we still needed to tune MLH predictions into our time management.

**Comment by mooskagh** [comment]
Let's close that for now, and have a separate issue for tuning/debugging the new time manager.
