### ISSUE TITLE
Illegal searchmoves crash the app

### ISSUE THREAD

**Issue by fohristiwhirl** [LeelaChessZero/lc0#899]
Illegal `searchmoves` crash the app, e.g.

```
uci
position startpos
go infinite searchmoves e2e5
```

**Comment by Naphthalin** [comment]
Just checked, still crashes. Is this an issue which should be solved by the engine (and not the GUI), and is it specified in UCI protocol or so?

**Comment by fohristiwhirl** [comment]
I don't think UCI says anything. It's certainly reasonable to blame the GUI, though one might take the view that inputs should be sanity checked. I imagine it's low priority.

(The issue in Nibbler that triggered this was resolved long ago.)

**Comment by Mardak** [comment]
What's the expected behavior? The main crash is probably in `PickNodeToExtend` when it moves from depth 1 to 2 and tries to access `best_edge`:
https://github.com/LeelaChessZero/lc0/blob/ad4b5f2c1db68c8120ad77c33a748bef724b053f/src/mcts/search.cc#L1022-L1026

If search just continues with node as search root but treats it `is_root_node = false`, then root filtering won't happen and search will continue as if there was no `searchmoves`

**Comment by fohristiwhirl** [comment]
> What's the expected behavior?

In a perfect world, filter the searchmoves list around parse time and delete all illegal moves, possibly reducing the list's length to 0 (in which case there are no searchmoves).

But it's not very important.

**Comment by borg323** [comment]
We should fix the crash, so reopenning.
