### ISSUE TITLE
Lc0's drawishness, and why it's the tip of the iceburg of a crippling local optimum:

### ISSUE THREAD

**Issue by RollYrOwn** [LeelaChessZero/lc0#903]
I'm sure most of you are aware of the final game of the TCEC rapid bonus (Season 15).  For your convenience, I'll link it here:  https://cd.tcecbeta.club/archive.html?season=15&div=rapid&game=546

It can be described fairly easily though - Leela is in incremental time against Jonny in an endgame that seems overwhelming, as Leela has a rook, a queen, and a pawn, against Jonny's queen and three pawns.  The black pawns are on the f-h files and still on Black's side of the board.  Black is unable to move them without material loss.  White's pawn is on the h file in a ram against Black's h-pawn.  Here is a fen from the final position:
3R4/5pk1/6p1/7p/6qP/8/5Q1K/8 b - - 100 124 

Leela's evaluation of the position ranged from winning chances of over 90%, to merely 70%, back up to 90%, eventually meandering down to zero.

At the time, and despite the usual hysteria in the chatroom, I didn't think it was a big deal: Leela chronically mishandles positions like this - there are just too many reasonable moves, and too much space for the queens to go.   MCTS (modified) breaks down - the search is too narrow, there are too many reasonable moves, and positional progress is too far away and requires too much specificity for Leela to gradually find the way.  It turns out that even engines - _even Neural Networks who do nothing but find patterns without prejudice_ find Queen endgames difficult to generalize.  When I explored the position with Nibbler, my belief that time trouble wasn't a factor was confirmed - I found the position temporally closest to a progress point, and let Leela just ponder it.  It didn't matter how much time she had.  **But so what**?  A missed win here and there isn't the end of the world: all engines have their blind spots, and Leela has an ability to grind out positional wins that's at times breathtaking.

After thinking about it, I realized that it was **a much bigger problem** than the occasional missed win.  Look at the fen again.  The ingredients in real chess are common - a wide open board, and the queens are still on, and there's no way to generalize a difference between the winning, drawing, and losing moves by pattern matching; almost all moves are at least reasonable.

**

- **TL;DR** MCTS has problems handling endings with the queens on and just a few pawns left.

**

The problem is this: _Leela's knows from her training to avoid these positions_.  Most games will be drawn, even with otherwise winning factors - an extra rook (as in the Jonny game) is a good example.  When there **is** a decisive game, often it will be resolved by accident, and the win and loss will be unpredictable.  So they aren't simply neutral, they're treacherous.

This self-knowledge has a cascading effect throughout Leela's entire game.  Sometimes it takes an amusing form: as in Leela's end-of-game habit of sacrificing her queen and then winning by rook and king when she's up by at least a queen and a rook.  **She does this consistently.**

We've all seen games where Leela has a direct attack on the enemy king, swaps off queens, and usually the momentum allows her to squeeze enough out of the position for a won endgame.  Sometimes the momentum isn't enough, and people complain about a missed win.

Lets go earlier in a typical game. Leela will, as white, often allow a symmetrical pawn formation to occur with an advantage of a single tempo just to get the queens off.  Even against opponents she has an advantage of hundreds of elo, she draws.

The problem even pops up in her favored openings, and in the positions she's most accurate in.  T40 is the most accurate chess NN we've ever created, and possibly ever created by anyone.  It's so accurate, in fact, that it hasn't bothered to explore the Ruy Lopez much beyond the Berlin defense and the open spanish.  Why would it ever look beyond a defense where the queens come off almost automatically, and leaving both sides with play?  Its accuracy has let it know that if the position can open up, queens are a problem.

The more games you examine, the more openings you see being handled sub-optimally (or not explored at all), the more openings you see Leela spending far more time than earlier series ever did - I'm thinking of Leela's obsession with the Four Knights Game - you'll realize that they aren't a bunch of individual problems.  They are solutions to a single, unifying problem.

I realize that fixing it isn't trivial, and the best that can be managed may be an imperfect solution.  But I hope this doesn't get buried under the huge "to-do" list.  Too much time and effort goes into making Leela efficient and accurate only for her efficiency and accuracy to work against her.

**

- **TL;DR** MCTS' problem with queen endgames poisons the rest of her game, and makes her training work against her.

**

**Comment by gonzalezjo** [comment]
I am not entirely convinced that the problem is inherent to MCTS or pruning possible moves. The entire idea behind using MCTS and a policy network stems from the idea that in Go, it’s (like in these queen endgames) very hard to write a generalized algorithm to score the position and prune out possible moves. I would think that this is where--if not for tablebases and sheer NPS--Leela would in theory be able to crush most traditional engines, with proper training. 


My theory for Leela’s woes in endgames with many possible moves is that the huge number of decent moves with similar scores causes two huge problems for the T40 network: 1) low search depth, and 2) massive influence from temperature.  


I’m reminded a lot of the issues Leela (Go) had with ladders when it was trained with too few nodes and too small a network. You wouldn’t ever be able to get Leela into a position where ladders would be problematic (similar to how Leela Chess manages to avoid queen endgames) but that didn’t change the fact that ladders simply weren’t understood well. 


Low search depth from positions with too many good nodes is (hopefully) addressed through Tilps’ KLD stuff. T53 showed that zero temperature probably isn’t the best option, but it would be interesting to see how it evaluated the position from TCEC, as compared to earlier T5x nets.

**Comment by TesseractA** [comment]
The major problem here is that the criteria for scoring a position as 'good' or 'bad' are entirely dependent upon emergent factors. The current PUCT algorithm will average in each position into the final evaluations. This is absolutely great for regions of low volatility, because one wrong answer will make the difference between a 'correct' scoring and an 'incorrect' scoring. It's much harder to go wrong in regions of lower volatility, which is one reason why LCzero wins tend to be less tactical.
As gonzalezjo mentioned, Tilps implemented a novel idea with the KLD threshold, searching more through regions of higher volatility. Theoretically, such a change should reduce volatility in places that were once more volatile, but since it needed to be balanced with strength of play, it's still not entirely a magic trick.

The problem with PUCT is, that in positions with highly specific variations over the course of N of moves, policy alone will search for wrong moves along the way. Since shoddy 'knowledge' like this is applied during training, the network will also have trouble with long-sequence evaluations. Henceforth, we have a chicken and egg problem; who will lay the egg (the training necessary to learn from), and what creates the chicken that lays the egg (the trainer necessary to create training)? This is where non-zero scoring criterion and/or trainers should probably step in for further optimization. 

Then again, what do I know; maybe the more 'general' approach is objectively better for neural networks instead of ever sinking properly into a permanently chess-specific approach to neural network training.

**Comment by Naphthalin** [comment]
As far as I can tell,
- the multiple queens problem was immanent for T30, but the change in board representation has solved this issue from T40 on
- T60 isn't drawish anymore to any means; if anything, it occasionally pushes too hard, but it is much stronger and more consistent than e.g. T10 was
- the "endgame trolling" seems to be going away as intended when using MLH in training+search

@RollYrOwn are there other things in this issue which I missed and aren't resolved by now?

**Comment by RollYrOwn** [comment]
Just checking old threads.

@Naphthalin no, not really: T60 is much better on these issues.  It still handles open positions with queens awkwardly; I think it's the number of reasonable moves and the difficulty there is in generalizing these types of positions, but that's way beyond the scope of an "issue".
