### ISSUE TITLE
Consider to not use error stream (cerr) for printing normal information

### ISSUE THREAD

**Issue by nguyenpham** [LeelaChessZero/lc0#977]
I know using the error stream may make the printing of Lc0 in red color in some systems. They may look more impressive or take more notices. However, IMO, it is a wrong use. For some chess GUIs, error messages from error stream may be printed in different windows and/or do some (wrong) alerts to users.

IMO, Lc0 is good enough to impress users by its strength and skills. For long term use, print out normal information in red color is almost useless too and may make users ignore real error messages.

In the attached image, Lc0 prints its name in red (may be accepted), but some other info in red too (overused):

<img width="1099" alt="Screen Shot 2019-11-01 at 5 06 47 pm" src="https://user-images.githubusercontent.com/1370755/68007576-1eb3ae80-fcd0-11e9-8870-80db15e6fd57.png">

**Comment by Naphthalin** [comment]
Does v0.25.1 still behave like this on your system?

**Comment by nguyenpham** [comment]
Still. Note that that chess GUI prints red for messages start with keyword "error" or one used stderr. Most below red messages are used stderr even they are not error messages.

<img width="835" alt="Screen Shot 2020-05-03 at 11 43 12 am" src="https://user-images.githubusercontent.com/1370755/80896598-81473f00-8d33-11ea-824b-72278902571b.png">

**Comment by mooskagh** [comment]
As stdout is reserved for UCI communication, we need a separate channel to communicate auxiliary information.
Stderr is the common way to do that. Some of that data is actually not even printed by us but rather by external libraries (tensorflow or cudnn), and we can do nothing about it.

This issue is infeasible to fix, therefore I'm inclined to close this issue.
